# Generated by Django 3.2.8 on 2021-10-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_app', '0002_delete_enrolledcourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='student', to='index_app.Course'),
        ),
    ]
